<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Анализатор страниц</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <style>
    .card {
        border: 1px, solid, #d8d8d8ff;
        background-color: #f3f3f3ff;
        padding: 20px;
        margin: 0 auto;
        width: 50rem;
        height: auto;
        font-family: 'Montserrat', sans-serif;
    }
    h1 {
        text-align: left;
        margin-left: 17px;
        margin-top: 20px;
    }
    .form-control {
        height: 50px;
    }
    .button {
    padding: 0;
    font-size: 1rem;
    height: 50px;
    width: 120px;
    line-height: 50px;
    border: 1px solid #0d6efd;
    }
    
    p {
        font-size: 20px;
        color: #676767ff;
    }
    .invalid-feedback {
        color: #dc3545;
    }
    .table, td, th {
        border: 1px, solid, #d8d8d8ff;
        text-align: left;
    }
    .sites {
        font-size: 50px;
        padding-left: 290px;
    }
    </style>
</head>
<body>
        <?php if (!empty($errors)): ?>
            <?= $this->fetch('_nav.phtml') ?>
            <?= $this->fetch('_form.phtml', ['url' => $url, 'flash' => $flash]) ?>
            <?php else: ?>
            <?= $this->fetch('_nav.phtml') ?>
            <h1 class="sites">Сайты</h1>
            <div class="container text-center">
                <table class="table table-hover" data-test="urls">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Имя</th>
                            <th>Последняя проверка</th>
                            <th>Код ответа</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($urls as $url): ?>
                            <tr>
                                <td><?= htmlspecialchars($url['id']) ?></td>
                                <td><a href="<?= $router->urlFor('url.show', ['id' => $url['id']]) ?>"><?= htmlspecialchars($url['name']) ?></a></td>
                                <td>
                                    <?php
                                    $lastCheck = $url['last_check'] ?? null;
                                    if ($lastCheck instanceof \DateTimeInterface) {
                                        $formattedDate = $lastCheck->format('Y-m-d H:i:s');
                                        echo htmlspecialchars($formattedDate);
                                    }
                                    ?>
                                </td>
                                <td><?= htmlspecialchars($url['status_code'] ?? 'N/A') ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        <?php endif; ?>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>