<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>Анализатор страниц</title>
    <style>
    .table, td, th {
        border: 1px, solid, #d8d8d8ff;
        text-align: left;
    }
    h1 {
        font-size: 40px;
        padding-left: 325px;
        padding-top: 20px;
    }
    .form {
        padding-left: 325px;
    }
    </style>
</head>
<body>
    <?= $this->fetch('_nav.phtml') ?>
    <?php if (!empty($flash['success'])): ?>
        <?php foreach ($flash['success'] as $message): ?>
            <div class="alert alert-success" role="alert">
                <?= htmlspecialchars($message) ?>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
    <?php if (!empty($flash['error'])): ?>
        <?php foreach ($flash['error'] as $message): ?>
            <div class="alert alert-error" role="alert">
                <?= htmlspecialchars($message) ?>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>

    <h1 class="mb-1">Сайт <?= htmlspecialchars($url->getName()) ?></h1>
    <div class="container mt-4">
        <div class="container text-center">
            <table class="table table-hover" data-test="url">
                <tbody>
                    <tr>
                        <td>ID</td>
                        <td><?= htmlspecialchars($url->getId()) ?></td>
                    </tr>
                    <tr>
                        <td>Имя</td>
                        <td><?= htmlspecialchars($url->getName()) ?></td>
                    </tr>
                    <tr>
                        <td>Дата создания</td>
                        <td><?= htmlspecialchars($url->getCreatedAt()) ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <h1 class="mb-4">Проверки</h1>
        <form action="<?= $router->urlFor('url.post.check', ['id' => $url->getId()]) ?>" method="post" class="form mb-4">
            <input type="submit" value="Запустить проверку" class="btn btn-primary">
        </form>
    <div class="container mt-4">
        <div class="container text-center">
            <table class="table table-hover" data-test="checks">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Код ответа</th>
                    <th>h1</th>
                    <th>title</th>
                    <th>description</th>
                    <th>Дата создания</th>
                </tr>
            </thead>
            <tbody>
                <?php if (!empty($urlChecks)): ?>
                    <?php foreach ($urlChecks as $check): ?>
                    <tr>
                        <td><?= htmlspecialchars($check->getId()) ?></td>
                        <td><?= htmlspecialchars($check->getStatusCode()) ?></td>
                        <td><?= htmlspecialchars($check->getH1()) ?></td>
                        <td><?= htmlspecialchars($check->getTitle()) ?></td>
                        <td><?= htmlspecialchars($check->getDescription()) ?></td>
                        <td><?= htmlspecialchars($check->getCreatedAt()) ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <?php endif; ?>
        </div>
    </div>
