    <div class="container mt-5">
        <div class="card">
            <h1 class="mb-1">Анализатор страниц</h1>
            <div class="card-body">
                <p class="mb-4">Бесплатно проверяйте сайты на SEO пригодность</p>
                <form action="/urls" method="post">
                    <div class="d-flex align-items-start">
                        <div class="flex-grow-1">
                            <input type="text" id="url" name="url[name]" class="form-control me-4 <?= !empty($flash) ? 'is-invalid' : '' ?> mb-2" value="<?= htmlspecialchars(isset($url) ? $url->getName() : '') ?>" placeholder="https://www.example.com">
                                <?php if (!empty($flash)): ?>
                                        <div class="invalid-feedback"><?= htmlspecialchars($flash) ?></div>
                                <?php endif; ?>
                        </div>
                        <input type="submit" class="button btn btn-primary ms-4" value="Проверить">
                    </div>
                </form>
            </div>
        </div>
    </div>