<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Анализатор страниц</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <style>
    .card {
    border: 1px, solid, #d8d8d8ff;
    background-color: #f3f3f3ff;
    padding: 20px;
    margin: 0 auto;
    width: 50rem;
    height: auto;
    font-family: 'Montserrat', sans-serif;
    }
    h1 {
        text-align: left;
        margin-left: 17px;
        margin-top: 20px;
    }
    .form-control {
        height: 50px;
    }
    button {
    padding: 0;
    font-size: 1rem;
    height: 50px;
    width: 120px;
    line-height: 50px;
    border: 1px solid #0d6efd;
    }
    
    p {
        font-size: 20px;
        color: #676767ff;
    }
</style>
</head>
<body>
    <?= $this->fetch('_nav.phtml') ?>
    <?= $this->fetch('_form.phtml', ['flash' => $flash]) ?>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>
